export const LIBRARY_NAME = "Центральна міська бібліотека";

export const books = 
[
    { 
        title: "Кобзар", 
        author: "Тарас Шевченко", 
        year: 1840, 
        pages: 280, 
        genre: "Поезія" 
    },
    { 
        title: "Clean Code", 
        author: "Robert Martin", 
        year: 2008, 
        pages: 464, 
        genre: "Технічна література" 
    },
    { 
        title: "1984", 
        author: "George Orwell", 
        year: 1949, 
        pages: 328, 
        genre: "Антиутопія" 
    },
    { 
        title: "Майстер і Маргарита", 
        author: "Михайло Булгаков", 
        year: 1967, 
        pages: 448, 
        genre: "Роман" 
    },
    { 
        title: "Відьмак", 
        author: "Анджей Сапковський", 
        year: 1986, 
        pages: 320, 
        genre: "Фентезі" 
    }
];